### ISSUE TITLE
Creation de la table categorie

### ISSUE THREAD

**Issue by JessicaTsopgni** [JessicaTsopgni/biblioIUC#2]
Attribut de la table avec leur type : 
- **id** : int auto_increment not null,
- **name** : varchar(50) not null,
- **description** : varchar(200) null,
- **categorie_parent_id** : int null,
- **image** : varchar(100) null,
- **status** : smallint(6) not null

**Comment by willytchana** [comment]
Bonsoir @JessicaTsopgni,
Cette tâche a déjà été faite.
